//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<TaxDeclarationAttribute> TaxDeclarationAttributes { get; set; }
        public virtual DbSet<TaxDeclarationEntry> TaxDeclarationEntries { get; set; }
        public virtual DbSet<TaxDeclaration> TaxDeclarations { get; set; }
    }
}
