//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxDeclarationEntry
    {
        public int id { get; set; }
        public decimal value { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime modifiedAt { get; set; }
        public int attribute_id { get; set; }
        public Nullable<int> createdByRule_id { get; set; }
        public int taxDeclaration_id { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual TaxDeclarationAttribute TaxDeclarationAttribute { get; set; }
        public virtual TaxDeclaration TaxDeclaration { get; set; }
    }
}
